config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  resources :posts
  root 'app#index'

  get 'posts/page/(:page(.:format))', to: 'posts#index'
  get 'users/page/(:page(.:format))', to: 'users#index'
  
  get 'app/index'
  get 'app/about'

  get "/users/auth/:provider/callback", to: "sessions#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true, length: { minimum: 3 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :seo, as: :seoble
  has_many :comments, as: :commentable
  has_many :commentators, through: :comments, source: :user

  validates :title, :body, presence: true
  validates :title, length: { minimum: 3 }
end

app/models/seo.rb
class Seo < ApplicationRecord
  belongs_to :seoble, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: %i[vkontakte]

  has_one :seo, as: :seoble
  has_many :posts
  has_many :comments
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :Post
  has_many :commented_users, through: :comments, source: :commentable, source_type: :User

  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  end

  def about    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :exception
  prepend_view_path Rails.root.join("frontend")

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).page(params[:page]).per(3)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order(:created_at).page(params[:page]).per(3)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :visible)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def vkontakte
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Vkontakte") if is_navigational_format?
    else
      session["devise.vkontakte_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page(params[:page]).per(3)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :moderator, :creator, :banned)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app/_footer.html.slim
= render 'components/menu/menu'
p.copyright © All rights reserved

app/views/app/_header.html.slim
.row.pull-right
  .col-xl-4
    .header-top
      ul.authenticate-block
        - if user_signed_in?
          li
            span Hello, #{current_user.email}
          li.model-manage
            = link_to 'Log out', destroy_user_session_path, method: :delete, :class => "model-manage-item"
            = '|'
            = link_to 'My profile', edit_user_path(current_user), :class => "model-manage-item"
        - else
          li.model-manage
            = link_to 'Log in', new_user_session_path, :class => "model-manage-item"
            = link_to 'Register', new_user_registration_path, :class => "model-manage-item"
            = link_to "Sign in with VK", user_vkontakte_omniauth_authorize_path, :class => "model-manage-item"
.row
  .col-xl-12    
    = render 'components/menu/menu'

app/views/app/_menu.html.slim
nav.main-nav
  li
    = link_to 'Home', root_path
  li
    = link_to 'About me', app_about_url
  li
    = link_to 'Posts', posts_path
  li
    = link_to 'Users', users_path 

app/views/app/about.html.slim
article
  = 'This is \'about me\' page'
  section
    = 'Posts by moderators'
    - User.where(moderator: true).map do |user|
      ul.posts
        - user.posts.each do |post|
          li.post
            = post.inspect

app/views/app/index.html.slim
article Welcome to RoR Blog!

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = stylesheet_pack_tag 'application'
    
  body
    header.container
      = render '/app/header'
    main.container
      .notice-container
        p.notice
          = notice
        p.alert
          = alert

      = yield
    footer.container
      = render '/app/footer'
      = javascript_pack_tag 'application'

app/views/posts/_comment.html.slim
.post-comment
  .comment-author
    = "#{comment.user.name}:"
  .comment-body
    = comment.body

app/views/posts/_form.html.slim
= form_for post do |f|
  - if post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :visible
    = f.check_box :visible
  .actions = f.submit

app/views/posts/_post.html.slim
section.post
  = link_to post.title, post, :class => "post-title"
  .post-body
    = post.body
  .post-info
    .post-date
      = "Date: #{post.created_at.strftime("%Y-%m-%d")}"
    .post-user
      span.post-user-title Author:
      = link_to post.user.name, post.user
  - if user_signed_in?
    .model-manage
      = link_to 'Show', post, :class => "model-manage-item"
      = '|'
      = link_to 'Edit', edit_post_path(post), :class => "model-manage-item"
      = '|'
      = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete, :class => "model-manage-item"

app/views/posts/edit.html.slim
h1 Editing post

== render 'form', post: @post

.model-manage
  = link_to 'Show', @post, :class => "model-manage-item"
  = '|'
  = link_to 'Back', posts_path, :class => "model-manage-item"

app/views/posts/index.html.slim
article.posts-list
  h1.page-header
    = 'Blog posts'
  - @posts.each do |post|
    = render partial: 'post', collection: @posts
- if user_signed_in?
  .model-manage
    = link_to 'New Post', new_post_path, :class => "model-manage-item"
  p
    = paginate @posts

app/views/posts/new.html.slim
h1 New post

== render 'form', post: @post

= link_to 'Back', posts_path

app/views/posts/show.html.slim
article
  p#notice = notice
  h1.page-header
    = @post.title
  
  section.post
    .post-body
      = @post.body
    .post-info
      .post-date
        = "Date: #{@post.created_at.strftime("%Y-%m-%d")}"
      .post-user
        span.post-user-title Author:
        = link_to @post.user.name, @post.user
  - if user_signed_in?
    .model-manage
      = link_to 'Edit', edit_post_path(@post), :class => "model-manage-item"
      = '|'
      = link_to 'Destroy', @post, data: { confirm: 'Are you sure?' }, method: :delete, :class => "model-manage-item"
  p
    strong Visible:
    = @post.visible
  section.post-comments
    h2 Comments:
    - @comments.each do |comment|
      = render partial: 'comment', collection: @comments
    p
      = paginate @comments

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :moderator
    = f.check_box :moderator
  .field
    = f.label :creator
    = f.check_box :creator
  .field
    = f.label :banned
    = f.check_box :banned
  .actions = f.submit

app/views/users/_user.html.slim
tr
td = user.name
td = user.email
td = user.moderator
td = user.creator
td = user.banned
- if user_signed_in?
    td = link_to 'Show', user
    td = link_to 'Edit', edit_user_path(user)
    td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

.model-manage

  = link_to 'Show', @user, :class => "model-manage-item"
  = '|'
  = link_to 'Back', users_path, :class => "model-manage-item"

app/views/users/index.html.slim
article
  h1.page-header Registered users

  table.users-table
    thead
    
      tr
        th Name
        th Email
        th Moderator
        th Creator
        th Banned
        - if user_signed_in? 
          th[colspan="3"] Manage

    tbody
      - @users.each do |user|
        = render partial: 'user', collection: @users 
  p
  = paginate @users

  .model-manage
    = link_to 'New User', new_user_path, :class => "model-manage-item"

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
article
  p#notice = notice

  p
    strong Name:
    = @user.name
  p
    strong Email:
    = @user.email
  p
    strong Moderator:
    = @user.moderator
  p
    strong Creator:
    = @user.creator
  p
    strong Banned:
    = @user.banned
  .model-manage
    = link_to 'Edit', edit_user_path(@user), :class => "model-manage-item"
    = '|'
    = link_to 'Back', users_path, :class => "model-manage-item"